---
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
linters:
  enable:
    - gosec
    - unconvert
    - gocyclo
    - goconst
    - goimports
    - gocritic
    # - govet
    - revive
linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable:
      - shadowing
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
